docker_repo: docker-ce.repo

# Docker user
docker_user: ramarmito

# Web server
web_docker_img_name: web
web_docker_img_tag: latest
web_container_name: webserver
web_ports: 8080:8080
web_dockerfile_path: docker/web/

# DB server
db_docker_img_name: db
db_docker_img_tag: latest
db_container_name: dbserver
db_ports: 6603:3306
db_dockerfile_path: docker/db/
