---
# tasks file for lamp_docker
- name: Create Docker directory
  file:
    path: docker
    state: directory

- name: Build web server Docker image from Dockerfile
  docker_image:
    name: "{{ web_docker_img_name }}"
    build:
      path: "{{ web_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: web_docker_img

- name: Build DB server Docker image from Dockerfile
  docker_image:
    name: "{{ db_docker_img_name }}"
    build:
      path: "{{ db_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: db_docker_img

- name: Clear IPTables filter
  shell: iptables -F; iptables -X
  when: web_docker_img.changed or db_docker_img.changed

- name: Restart Docker
  service:
    name: docker
    state: restarted
  when: web_docker_img.changed or db_docker_img.changed

# Tasks files for roles/run docker container
- name: Run Web server container
  docker_container:
    name: "{{ web_container_name }}"
    image: "{{ web_docker_img_name }}:{{ web_docker_img_tag }}"
    privileged: yes
    published_ports: "{{ web_ports }}"

- name: Run DB server container
  docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_docker_img_name }}:{{ db_docker_img_tag }}"
    privileged: yes
    published_ports: "{{ db_ports }}"
